
name: test workflow

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  build_and_test:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version : ['8.x']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: dorny/paths-filter@v3
        id: project_change_filter
        with:
          filters: |
              project_1_files_changed:
              - 'project_1/**'
              project_2_files_changed:
              - 'project_2/**'

      - name : DEBUG
        run : |
            echo "hello world"
            echo "project_1_files_changed: ${{steps.project_change_filter.outputs.project_1_files_changed}}"
            echo "project_2_files_changed: ${{steps.project_change_filter.outputs.project_2_files_changed}}"
            echo "debug info:"
            echo "The current workspace of GITHUB_WORKSPACE is:"
            echo $GITHUB_WORKSPACE
            echo "The current workspace of github.workspace is: echo ${{github.workspace}}"
            dotnet --version
      - name: Test project1
        if: steps.project_change_filter.outputs.project_1_files_changed == 'true'
        run: |
            echo "running CI because project 1 files changed"
      - name: Test project2
        if: steps.project_change_filter.outputs.project_2_files_changed == 'true'
        run: |
            echo "running CI because project 2 files changed"
            


