
name: test workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  testing_how_needs_work:
    strategy:
      matrix:
        version : ['8.x', '6.x']
    runs-on: ubuntu-latest
    outputs:
      simple_value_1: ${{ steps.step_1.outputs.test_value }}
    steps:
      - id: step_1
        run: |
          version="${{ matrix.version }}"
          echo "test_value_${version}=testing_w_static_value" >> "$$GITHUB_OUTPUT"

  build_and_test:
    needs: testing_how_needs_work
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version : ['8.x']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: dorny/paths-filter@v3
        id: project_change_filter
        with:
          filters: |
              project_1_files_changed:
              - 'project_1/**'
              project_2_files_changed:
              - 'project_2/**'

      - name : DEBUG
        run : |
            echo "hello world"
            echo "project_1_files_changed: ${{steps.project_change_filter.outputs.project_1_files_changed}}"
            echo "project_2_files_changed: ${{steps.project_change_filter.outputs.project_2_files_changed}}"
            echo "debug info:"
            echo "The current workspace of GITHUB_WORKSPACE is:"
            echo $GITHUB_WORKSPACE
            echo "The current workspace of github.workspace is: echo ${{github.workspace}}"
            dotnet --version
          
      - name: test in-between job data transfers
        run : |
            echo '${{ toJson(needs.testing_how_needs_work.outputs) }}'

      - name: call local action for project 1
        # if: steps.project_change_filter.outputs.project_1_files_changed == 'true' && github.event.review.state == 'approved'
        uses: ./.github/actions/wf_base_action
        with: 
          test-project-folder: ./project_1
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Test project2
        if: steps.project_change_filter.outputs.project_2_files_changed == 'true' && github.event.review.state == 'approved'
        run: |
            echo "running CI because project 2 files changed"

